//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//


package devtime.model.requests;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 *
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="api_key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="start_time" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="end_time" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         <element name="project_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="os" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="files_container">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="file_container" maxOccurs="unbounded">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="file_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             <element name="rows_count" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "apiKey",
    "startTime",
    "endTime",
    "projectName",
    "os",
    "filesContainer"
})
@XmlRootElement(name = "Activity")
public class Activity {

    @XmlElement(name = "api_key", required = true)
    protected String apiKey;
    @XmlElement(name = "start_time", required = true)
    protected long startTime;
    @XmlElement(name = "end_time", required = true)
    protected long endTime;
    @XmlElement(name = "project_name", required = true)
    protected String projectName;
    @XmlElement(name = "os", required = true)
    protected String os;
    @XmlElement(name = "files_container", required = true)
    protected Activity.FilesContainer filesContainer;

    public Activity() {
    }

    public Activity(String apiKey, long startTime, long endTime, String projectName, String os, FilesContainer filesContainer) {
        this.apiKey = apiKey;
        this.startTime = startTime;
        this.endTime = endTime;
        this.projectName = projectName;
        this.os = os;
        this.filesContainer = filesContainer;
    }

    /**
     * Gets the value of the ApiKey property.
     *
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * Sets the value of the ApiKey property.
     *
     */
    public void setApiKey(String value) {
        this.apiKey = value;
    }

    /**
     * Gets the value of the startTime property.
     *
     */
    public long getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     *
     */
    public void setStartTime(long value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     *
     */
    public long getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     *
     */
    public void setEndTime(long value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the projectName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * Sets the value of the projectName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setProjectName(String value) {
        this.projectName = value;
    }

    /**
     * Gets the value of the os property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOs() {
        return os;
    }

    /**
     * Sets the value of the os property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOs(String value) {
        this.os = value;
    }

    /**
     * Gets the value of the filesContainer property.
     *
     * @return
     *     possible object is
     *     {@link Activity.FilesContainer }
     *
     */
    public Activity.FilesContainer getFilesContainer() {
        return filesContainer;
    }

    /**
     * Sets the value of the filesContainer property.
     *
     * @param value
     *     allowed object is
     *     {@link Activity.FilesContainer }
     *
     */
    public void setFilesContainer(Activity.FilesContainer value) {
        this.filesContainer = value;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     *
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="file_container" maxOccurs="unbounded">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="file_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   <element name="rows_count" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fileContainer"
    })
    public static class FilesContainer {

        @XmlElement(name = "file_container", required = true)
        protected List<Activity.FilesContainer.FileContainer> fileContainer;

        public FilesContainer() {
            this.fileContainer = new ArrayList<Activity.FilesContainer.FileContainer>();
        }

        /**
         * Gets the value of the fileContainer property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fileContainer
         * property.
         * </p>
         *
         * <p>
         * For example, to add a new item, do as follows:
         * </p>
         *
         * <pre>
         * getFileContainer().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Activity.FilesContainer.FileContainer }
         * </p>
         *
         *
         * @return
         *         The value of the fileContainer property.
         */
        public List<Activity.FilesContainer.FileContainer> getFileContainer() {
            if (fileContainer == null) {
                fileContainer = new ArrayList<>();
            }
            return this.fileContainer;
        }


        /**
         * <p>Java class for anonymous complex type</p>.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.</p>
         *
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="file_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         <element name="rows_count" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fileName",
            "rowsCount"
        })
        public static class FileContainer {

            @XmlElement(name = "file_name", required = true)
            protected String fileName;
            @XmlElement(name = "rows_count")
            protected int rowsCount;

            public FileContainer(String fileName, int rowsCount) {
                this.fileName = fileName;
                this.rowsCount = rowsCount;
            }

            /**
             * Gets the value of the fileName property.
             *
             *         urn
             *         possible object is
             *     {@link String }
             *
             */
            public String getFileName() {
                return fileName;
            }

            /**
             * Sets the value of the fileName property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setFileName(String value) {
                this.fileName = value;
            }

            /**
             * Gets the value of the rowsCount property.
             *
             */
            public int getRowsCount() {
                return rowsCount;
            }

            /**
             * Sets the value of the rowsCount property.
             *
             */
            public void setRowsCount(int value) {
                this.rowsCount = value;
            }

        }


        public void add(FileContainer fileContainer2) {
            this.fileContainer.add(fileContainer2);
        }


        public void addAll(FilesContainer filesContainer2) {
            this.fileContainer.addAll(filesContainer2.getFileContainer());
        }

    }

}
